apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-logs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-airflow-logs
  nfs:
    server: 172.31.3.234
    path: /tmp/k8spv